export const supplyMarket = [
  {
    id: 1,
    imaageUrl: "assets/images/WBTC.svg",
    text: "WBTC",
    tag: "0%",
    wallet: "0 BTC",
    collateral: false,
    collaterable: true,
  },
  {
    id: 2,
    imaageUrl: "/assets/images/Ethereum.svg",
    text: "ETH",
    tag: "0%",
    wallet: "0 ETH",
    collateral: false,
    collaterable: true,
  },
  {
    id: 3,
    imaageUrl: "assets/images/USDC.svg",
    text: "USDC",
    tag: "0%",
    wallet: "0 USDC",
    collateral: false,
    collaterable: false,
  },
  {
    id: 4,
    imaageUrl: "assets/images/XSGD.png",
    text: "XSGD",
    tag: "0%",
    wallet: "0 XSGD",
    collateral: false,
    collaterable: false,
  },
  {
    id: 5,
    imaageUrl: "assets/images/XIDR.png",
    text: "XIDR",
    tag: "0%",
    wallet: "0 XIDR",
    collateral: false,
    collaterable: false,
  },
  {
    id: 6,
    imaageUrl: "assets/images/NZDS.png",
    text: "NZDS",
    tag: "0%",
    wallet: "0 NZDS",
    collateral: false,
    collaterable: false,
  },
];

export const borrowMarket = [
  {
    id: 1,
    imaageUrl: "assets/images/WBTC.svg",
    text: "WBTC",
    tag: "0%",
    wallet: "0 WBTC",
    liquidity: "$0",
  },
  {
    id: 2,
    imaageUrl: "/assets/images/Ethereum.svg",
    text: "ETH",
    tag: "0%",
    wallet: "0 ETH",
    liquidity: "$0",
  },
  {
    id: 3,
    imaageUrl: "assets/images/USDC.svg",
    text: "USDC",
    tag: "0%",
    wallet: "0 USDC",
    liquidity: "$0",
  },
  {
    id: 4,
    imaageUrl: "assets/images/XSGD.png",
    text: "XSGD",
    tag: "0%",
    wallet: "0 XSGD",
    liquidity: "$0",
  },
  {
    id: 5,
    imaageUrl: "assets/images/XIDR.png",
    text: "XIDR",
    tag: "0%",
    wallet: "0 XIDR",
    liquidity: "$0",
  },
  {
    id: 6,
    imaageUrl: "assets/images/NZDS.png",
    text: "NZDS",
    tag: "0%",
    wallet: "0 NZDS",
    liquidity: "$0",
  },
];
